info:
  version: 0.0.2
  generated_at: '2025-08-13T11:22:58.069Z'
parameters:
  person:
    id: person
    label: Person
    datatype: text
    type: default
  institution:
    id: institution
    label: Institution
    datatype: dropdown
    type: default
    options:
      - CNRC
      - Georgia Institute of Technology
      - Mondragon Unibertsitatea
      - Université de Mons
      - KIT Karlsruhe
      - IFW - Universität Stuttgart
      - AMRC - University of Sheffield
      - Centrale Lyon ENISE
      - CIIRC - CTU Prague
      - University of Ljubljana
      - University of Tokyo
      - Keio University
      - PTW - TU Darmstadt
      - IFT - TU Wien
      - ETH Zürich, Inspire
      - ISF - TU Dortmund
      - MTI - RWTH Aachen
      - MAL - University of British Columbia
      - SECO
  machine:
    id: machine
    label: Machine
    datatype: text
    type: default
  experiment:
    id: experiment
    label: Experiment ID/Number
    datatype: text
    type: default
  process:
    id: process
    label: Process
    datatype: dropdown
    type: default
    options:
      - Milling
      - Drilling
      - Grinding
      - Turning
      - Reaming
      - Thread Cutting
      - Thread Forming
      - Thread Milling
  workpiece_material:
    id: workpiece_material
    label: Workpiece Material
    datatype: text_suggestions
    type: default
    options:
      - C45
      - Steel
  cutting_speed:
    id: cutting_speed
    label: Cutting Speed
    datatype: float
    unit: m/min
    type: range
  feed_per_tooth:
    id: feed_per_tooth
    label: Feed per Tooth
    datatype: float
    unit: mm/tooth
    type: range
  feed_per_rev:
    id: feed_per_rev
    label: Feed per Revolution
    datatype: float
    unit: mm/rev
    type: range
  doc_axial:
    id: doc_axial
    label: Depth of Cut (axial)
    datatype: float
    unit: mm
    type: range
  doc_radial:
    id: doc_radial
    label: Depth of Cut (radial)
    datatype: float
    unit: mm
    type: range
  doc:
    id: doc
    label: Depth of Cut
    datatype: float
    unit: mm
    type: range
  workpiece_diameter:
    id: workpiece_diameter
    label: Workpiece Diameter
    datatype: float
    unit: mm
    type: default
  tool_diameter:
    id: tool_diameter
    label: Tool Diameter
    datatype: float
    unit: mm
    type: default
  tool_tooth_count:
    id: tool_tooth_count
    label: Tool Tooth Count
    datatype: int
    type: default
  tool_material:
    id: tool_material
    label: Tool Material
    datatype: text_suggestions
    type: default
    options:
      - Carbide (P40)
      - Carbide
      - MCD
      - Ceramic
      - PCD
  tool_offset:
    id: tool_offset
    label: Tool Offset
    datatype: float
    unit: mm
    type: default
  coolant:
    id: coolant
    label: Coolant
    datatype: dropdown
    type: default
    options:
      - Dry
      - Air
      - MMQ
      - Flood
      - Oil
  sth_mac:
    id: sth_mac
    label: STH Mac Address
    datatype: text
    type: implementation
  stu_mac:
    id: stu_mac
    label: STU Mac Address
    datatype: text
    type: implementation
  tool_breakage:
    id: tool_breakage
    label: Tool Breakage in this cut
    datatype: boolean
    type: default
  first_tool_wear_exceeded:
    id: first_tool_wear_exceeded
    label: Tool Wear Exceeded (First Peripheral CE)
    datatype: boolean
    type: default
  first_wear_mark_width:
    id: first_wear_mark_width
    label: Avg. Wear Mark Width (First Peripheral CE)
    datatype: float
    unit: mm
    type: default
  first_max_wear_mark_width:
    id: first_max_wear_mark_width
    label: Max. Wear Mark Width (First Peripheral CE)
    datatype: float
    unit: mm
    type: default
  second_wear_mark_width:
    id: second_wear_mark_width
    label: Avg. Wear Mark Width (Second Peripheral CE)
    datatype: float
    unit: mm
    type: default
  second_max_wear_mark_width:
    id: second_max_wear_mark_width
    label: Max. Wear Mark Width (Second Peripheral CE)
    datatype: float
    unit: mm
    type: default
  second_tool_wear_exceeded:
    id: second_tool_wear_exceeded
    label: Tool Wear Exceeded (Second Peripheral CE)
    datatype: boolean
    type: default
  twm_layer:
    id: twm_layer
    label: Layer Number
    datatype: int
    type: default
  pictures:
    id: pictures
    label: Pictures
    datatype: file
    type: default
  comment:
    id: comment
    label: Comment
    datatype: text_box
    type: default
  direction:
    id: direction
    label: Milling Direction
    datatype: dropdown
    type: default
    options:
      - Climb
      - Conventional
  n_cuts:
    id: n_cuts
    label: Total Number of Cuts at Inspection
    datatype: int
    type: default
  n_measurement:
    id: n_measurement
    label: Measurement Number in Experiment
    datatype: int
    type: default
  first_pictures:
    id: first_pictures
    label: Pictures of First Peripheral Cutting Edge
    datatype: file
    type: default
  second_pictures:
    id: second_pictures
    label: Pictures of Second Peripheral Cutting Edge
    datatype: file
    type: default
  tool_r_at_0:
    id: tool_r_at_0
    label: Tool Radius at 0mm
    datatype: float
    unit: mm
    type: default
  tool_r_at_1:
    id: tool_r_at_1
    label: Tool Radius at 1mm
    datatype: float
    unit: mm
    type: default
  tool_r_at_2:
    id: tool_r_at_2
    label: Tool Radius at 2mm
    datatype: float
    unit: mm
    type: default
  tool_r_at_3:
    id: tool_r_at_3
    label: Tool Radius at 3mm
    datatype: float
    unit: mm
    type: default
  tool_r_at_4:
    id: tool_r_at_4
    label: Tool Radius at 4mm
    datatype: float
    unit: mm
    type: default
  tool_r_at_5:
    id: tool_r_at_5
    label: Tool Radius at 5mm
    datatype: float
    unit: mm
    type: default
  tool_r_at_6:
    id: tool_r_at_6
    label: Tool Radius at 6mm
    datatype: float
    unit: mm
    type: default
  first_peripheral_pictures:
    id: first_peripheral_pictures
    label: Pictures of First Peripheral Cutting Edge
    datatype: file
    type: default
  first_end_pictures:
    id: first_end_pictures
    label: Pictures of First End Cutting Edge
    datatype: file
    type: default
  second_peripheral_pictures:
    id: second_peripheral_pictures
    label: Pictures of Second Peripheral Cutting Edge
    datatype: file
    type: default
  second_end_pictures:
    id: second_end_pictures
    label: Pictures of Second End Cutting Edge
    datatype: file
    type: default
  abnormal_tool_wear:
    id: abnormal_tool_wear
    label: Abnormal Tool Wear Present
    datatype: boolean
    type: default
categories:
  general: General
  hardware: Hardware
  process: Process
  files: Files
  additional: Additional
  results: Results
  first_ce: First Cutting Edge
  second_ce: Second Cutting Edge
  wear: Overall Tool Wear
lists:
  requirement:
    - Required
    - Optional
    - Hidden
    - Restricted
  coolant:
    - Dry
    - Air
    - MMQ
    - Flood
    - Oil
  institution:
    - CNRC
    - Georgia Institute of Technology
    - Mondragon Unibertsitatea
    - Université de Mons
    - KIT Karlsruhe
    - IFW - Universität Stuttgart
    - AMRC - University of Sheffield
    - Centrale Lyon ENISE
    - CIIRC - CTU Prague
    - University of Ljubljana
    - University of Tokyo
    - Keio University
    - PTW - TU Darmstadt
    - IFT - TU Wien
    - ETH Zürich, Inspire
    - ISF - TU Dortmund
    - MTI - RWTH Aachen
    - MAL - University of British Columbia
    - SECO
  workpiece_material:
    - C45
    - Steel
  tool_material:
    - Carbide (P40)
    - Carbide
    - MCD
    - Ceramic
    - PCD
  process:
    - Milling
    - Drilling
    - Grinding
    - Turning
    - Reaming
    - Thread Cutting
    - Thread Forming
    - Thread Milling
  direction:
    - Climb
    - Conventional
profiles:
  twm1:
    id: twm_cirp_tool1
    name: CIRP TWM 1 (ae=2mm)
    pre:
      general:
        person:
          required: required
          description: Person responsible for conducting the measurement.
        institution:
          required: required
          description: CIRP institution at which the measurement is captured.
        machine:
          required: required
          description: Machine tool in which the measurement was conducted.
        process:
          required: restricted
          default: Milling
      process:
        workpiece_material:
          required: restricted
          default: '1.2379'
        cutting_speed:
          required: restricted
          default: 80
        feed_per_tooth:
          required: restricted
          default: 0.05
        doc_axial:
          required: restricted
          default: 5
        doc_radial:
          required: restricted
          default: 2
        tool_diameter:
          required: restricted
          default: 10
        tool_tooth_count:
          required: restricted
          default: 2
        tool_material:
          required: restricted
          default: Carbide (P40)
        coolant:
          required: restricted
          default: Dry
        direction:
          required: restricted
          default: Climb
      hardware:
        sth_mac:
          required: required
        stu_mac:
          required: required
    post:
      results:
        n_cuts:
          required: optional
          description: Total number of cuts performed by tool at this inspection.
        n_measurement:
          required: optional
          description: Measurement number in experiment (0 for inital tool measurement; then start from 1)
        tool_breakage:
          required: optional
          default: 'false'
          description: Has the tool failed during this run?
        abnormal_tool_wear:
          required: optional
          default: 'false'
          description: Signs of abnormal wear (buildup, chipping) in this run - Comment!
      wear:
        tool_r_at_0:
          required: optional
          description: Tool radius at a height of 0mm from the end (at the cutter's end)
        tool_r_at_1:
          required: optional
          description: Tool radius at a height of 1mm from the end
        tool_r_at_2:
          required: optional
          description: Tool radius at a height of 2mm from the end
        tool_r_at_3:
          required: optional
          description: Tool radius at a height of 3mm from the end
        tool_r_at_4:
          required: optional
          description: Tool radius at a height of 4mm from the end
        tool_r_at_5:
          required: optional
          description: Tool radius at a height of 5mm from the end
        tool_r_at_6:
          required: optional
          description: Tool radius at a height of 6mm from the end (reference - not in cut)
      first_ce:
        first_peripheral_pictures:
          required: optional
          description: Picture of the first cutting edge (peripheral)
        first_end_pictures:
          required: optional
          description: Picture of the first cutting edge (end)
      second_ce:
        second_peripheral_pictures:
          required: optional
          description: Picture of the second cutting edge (peripheral)
        second_end_pictures:
          required: optional
          description: Picture of the second cutting edge (end)
      additional:
        comment:
          required: optional
          description: Additional comments - describe abnormal wear or other information
  twm2:
    id: twm_cirp_tool2
    name: CIRP TWM 2 (ae=10mm)
    pre:
      general:
        person:
          required: required
          description: Person responsible for conducting the measurement.
        institution:
          required: required
          description: CIRP institution at which the measurement is captured.
        machine:
          required: required
          description: Machine tool in which the measurement was conducted.
        process:
          required: restricted
          default: Milling
      process:
        workpiece_material:
          required: restricted
          default: '1.2379'
        cutting_speed:
          required: restricted
          default: 80
        feed_per_tooth:
          required: restricted
          default: 0.05
        doc_axial:
          required: restricted
          default: 5
        doc_radial:
          required: restricted
          default: 10
        tool_diameter:
          required: restricted
          default: 10
        tool_tooth_count:
          required: restricted
          default: 2
        tool_material:
          required: restricted
          default: Carbide (P40)
        coolant:
          required: restricted
          default: Dry
        direction:
          required: restricted
          default: Climb
      hardware:
        sth_mac:
          required: required
        stu_mac:
          required: required
    post:
      results:
        n_cuts:
          required: optional
          description: Total number of cuts performed by tool at this inspection.
        n_measurement:
          required: optional
          description: Measurement number in experiment (0 for inital tool measurement; then start from 1)
        tool_breakage:
          required: optional
          default: 'false'
          description: Has the tool failed during this run?
        abnormal_tool_wear:
          required: optional
          default: 'false'
          description: Signs of abnormal wear (buildup, chipping) in this run - Comment!
      wear:
        tool_r_at_0:
          required: optional
          description: Tool radius at a height of 0mm from the end (at the cutter's end)
        tool_r_at_1:
          required: optional
          description: Tool radius at a height of 1mm from the end
        tool_r_at_2:
          required: optional
          description: Tool radius at a height of 2mm from the end
        tool_r_at_3:
          required: optional
          description: Tool radius at a height of 3mm from the end
        tool_r_at_4:
          required: optional
          description: Tool radius at a height of 4mm from the end
        tool_r_at_5:
          required: optional
          description: Tool radius at a height of 5mm from the end
        tool_r_at_6:
          required: optional
          description: Tool radius at a height of 6mm from the end (reference - not in cut)
      first_ce:
        first_peripheral_pictures:
          required: optional
          description: Picture of the first cutting edge (peripheral)
        first_end_pictures:
          required: optional
          description: Picture of the first cutting edge (end)
      second_ce:
        second_peripheral_pictures:
          required: optional
          description: Picture of the second cutting edge (peripheral)
        second_end_pictures:
          required: optional
          description: Picture of the second cutting edge (end)
      additional:
        comment:
          required: optional
          description: Additional comments - describe abnormal wear or other information
  milling:
    id: milling
    name: Milling (Generic)
    pre:
      general:
        person:
          required: optional
          description: Person responsible for the measurement.
        institution:
          required: optional
          description: Institution at which the measurement is captured.
        machine:
          required: optional
          description: Machine tool used for the measurement.
        experiment:
          required: optional
          description: Experiment number or ID to identify the measurement.
        process:
          required: optional
          default: Milling
          description: Measured process.
      process:
        workpiece_material:
          required: optional
          description: Material of the workpiece.
        cutting_speed:
          required: optional
        feed_per_tooth:
          required: optional
        doc_axial:
          required: optional
        doc_radial:
          required: optional
        tool_diameter:
          required: optional
        tool_tooth_count:
          required: optional
        tool_material:
          required: optional
        tool_offset:
          required: optional
          description: Tool offset from the control.
        coolant:
          required: optional
        direction:
          required: optional
      hardware:
        sth_mac:
          required: required
          description: MAC Address of the STH. Will be automatically set.
        stu_mac:
          required: required
          description: MAC Address of the STU. Will be automatically set.
    post:
      general:
        pictures:
          required: optional
          description: Pictures of the experiment; will be stored in the .hdf5 file.
        comment:
          required: optional
