info:
  version: 0.0.1
parameters:
  person:
    id: person
    label: Person
    datatype: text
    type: default
  institution:
    id: institution
    label: Institution
    datatype: dropdown
    type: default
    options:
      - TU Wien
      - TU München
      - ETH Zürich
  machine:
    id: machine
    label: Machine
    datatype: text
    type: default
  experiment:
    id: experiment
    label: Experiment ID/Number
    datatype: text
    type: default
  process:
    id: process
    label: Process
    datatype: dropdown
    type: default
    options:
      - milling
      - drilling
      - grinding
      - turning
      - reaming
      - shaping
      - thread_cutting
      - thread_milling
      - thread_forming
  workpiece_material:
    id: workpiece_material
    label: Workpiece Material
    datatype: text_suggestions
    type: default
    options:
      - S235
      - 4140
      - TiAl
      - Grade 5 Titanium
  cutting_speed:
    id: cutting_speed
    label: Cutting Speed
    datatype: float
    unit: m/min
    type: range
  feed_per_tooth:
    id: feed_per_tooth
    label: Feed per Tooth
    datatype: float
    unit: mm/tooth
    type: range
  feed_per_rev:
    id: feed_per_rev
    label: Feed per Revolution
    datatype: float
    unit: mm/rev
    type: range
  doc_axial:
    id: doc_axial
    label: Depth of Cut (axial)
    datatype: float
    unit: mm
    type: range
  doc_radial:
    id: doc_radial
    label: Depth of Cut (radial)
    datatype: float
    unit: mm
    type: range
  doc:
    id: doc
    label: Depth of Cut
    datatype: float
    unit: mm
    type: range
  workpiece_diameter:
    id: workpiece_diameter
    label: Workpiece Diameter
    datatype: float
    unit: mm
    type: default
  tool_diameter:
    id: tool_diameter
    label: Tool Diameter
    datatype: float
    unit: mm
    type: default
  tool_tooth_count:
    id: tool_tooth_count
    label: Tool Tooth Count
    datatype: int
    type: default
  tool_material:
    id: tool_material
    label: Tool Material
    datatype: text_suggestions
    type: default
    options:
      - PCD
      - Carbide
      - MCD
      - Ceramic
  tool_offset:
    id: tool_offset
    label: Tool Offset
    datatype: float
    unit: mm
    type: default
  coolant:
    id: coolant
    label: Coolant
    datatype: dropdown
    type: default
    options:
      - Flood
      - MMQ
      - …
  sth_mac:
    id: sth_mac
    label: STH Mac Address
    datatype: text
    type: default
  stu_mac:
    id: stu_mac
    label: STU Mac Address
    datatype: text
    type: default
processes:
  milling:
    label: Milling
    parameters:
      person: required
      institution: required
      machine: required
      experiment: required
      process: required
      workpiece_material: required
      cutting_speed: required
      feed_per_tooth: required
      feed_per_rev: hidden
      doc_axial: required
      doc_radial: required
      doc: hidden
      workpiece_diameter: hidden
      tool_diameter: required
      tool_tooth_count: required
      tool_material: required
      tool_offset: required
      coolant: required
      sth_mac: required
      stu_mac: required
  drilling:
    label: Drilling
    parameters:
      person: required
      institution: required
      machine: required
      experiment: required
      process: required
      workpiece_material: required
      cutting_speed: required
      feed_per_tooth: hidden
      feed_per_rev: required
      doc_axial: hidden
      doc_radial: hidden
      doc: optional
      workpiece_diameter: hidden
      tool_diameter: required
      tool_tooth_count: required
      tool_material: required
      tool_offset: required
      coolant: required
      sth_mac: required
      stu_mac: required
  grinding:
    label: Grinding
    parameters:
      person: required
      institution: required
      machine: required
      experiment: required
      process: required
      workpiece_material: required
      cutting_speed: required
      feed_per_tooth: hidden
      feed_per_rev: hidden
      doc_axial: hidden
      doc_radial: hidden
      doc: required
      workpiece_diameter: hidden
      tool_diameter: required
      tool_tooth_count: hidden
      tool_material: required
      tool_offset: hidden
      coolant: required
      sth_mac: required
      stu_mac: required
  turning:
    label: Turning
    parameters:
      person: required
      institution: required
      machine: required
      experiment: required
      process: required
      workpiece_material: required
      cutting_speed: required
      feed_per_tooth: hidden
      feed_per_rev: required
      doc_axial: hidden
      doc_radial: hidden
      doc: required
      workpiece_diameter: required
      tool_diameter: hidden
      tool_tooth_count: hidden
      tool_material: required
      tool_offset: required
      coolant: required
      sth_mac: required
      stu_mac: required
  reaming:
    label: Reaming
    parameters:
      person: required
      institution: required
      machine: required
      experiment: required
      process: required
      workpiece_material: required
      cutting_speed: required
      feed_per_tooth: hidden
      feed_per_rev: required
      doc_axial: hidden
      doc_radial: hidden
      doc: required
      workpiece_diameter: hidden
      tool_diameter: required
      tool_tooth_count: required
      tool_material: required
      tool_offset: required
      coolant: required
      sth_mac: required
      stu_mac: required
  shaping:
    label: Shaping
    parameters:
      person: required
      institution: required
      machine: required
      experiment: required
      process: required
      workpiece_material: required
      cutting_speed: required
      feed_per_tooth: hidden
      feed_per_rev: hidden
      doc_axial: hidden
      doc_radial: hidden
      doc: hidden
      workpiece_diameter: hidden
      tool_diameter: hidden
      tool_tooth_count: hidden
      tool_material: required
      tool_offset: required
      coolant: required
      sth_mac: required
      stu_mac: required
  thread_cutting:
    label: Thread Cutting
    parameters:
      person: required
      institution: required
      machine: required
      experiment: required
      process: required
      workpiece_material: required
      cutting_speed: required
      feed_per_tooth: hidden
      feed_per_rev: required
      doc_axial: hidden
      doc_radial: hidden
      doc: hidden
      workpiece_diameter: hidden
      tool_diameter: required
      tool_tooth_count: required
      tool_material: required
      tool_offset: required
      coolant: required
      sth_mac: required
      stu_mac: required
  thread_milling:
    label: Thread Milling
    parameters:
      person: required
      institution: required
      machine: required
      experiment: required
      process: required
      workpiece_material: required
      cutting_speed: required
      feed_per_tooth: required
      feed_per_rev: hidden
      doc_axial: hidden
      doc_radial: hidden
      doc: hidden
      workpiece_diameter: hidden
      tool_diameter: required
      tool_tooth_count: required
      tool_material: required
      tool_offset: required
      coolant: required
      sth_mac: required
      stu_mac: required
  thread_forming:
    label: Thread Forming
    parameters:
      person: required
      institution: required
      machine: required
      experiment: required
      process: required
      workpiece_material: required
      cutting_speed: required
      feed_per_tooth: hidden
      feed_per_rev: required
      doc_axial: hidden
      doc_radial: hidden
      doc: hidden
      workpiece_diameter: hidden
      tool_diameter: required
      tool_tooth_count: hidden
      tool_material: required
      tool_offset: required
      coolant: required
      sth_mac: required
      stu_mac: required
