info:
  version: 0.0.2
  generated_at: '2025-07-15T06:09:47.124Z'
parameters:
  person:
    id: person
    label: Person
    datatype: text
    type: default
  institution:
    id: institution
    label: Institution
    datatype: dropdown
    type: default
    options:
      - TU Wien
      - TU Darmstadt
  machine:
    id: machine
    label: Machine
    datatype: text
    type: default
  experiment:
    id: experiment
    label: Experiment ID/Number
    datatype: text
    type: default
  process:
    id: process
    label: Process
    datatype: dropdown
    type: default
    options:
      - Milling
      - Drilling
      - Grinding
      - Turning
      - Reaming
      - Thread Cutting
      - Thread Forming
      - Thread Milling
  workpiece_material:
    id: workpiece_material
    label: Workpiece Material
    datatype: text_suggestions
    type: default
    options:
      - C45
      - Steel
  cutting_speed:
    id: cutting_speed
    label: Cutting Speed
    datatype: float
    unit: m/min
    type: range
  feed_per_tooth:
    id: feed_per_tooth
    label: Feed per Tooth
    datatype: float
    unit: mm/tooth
    type: range
  feed_per_rev:
    id: feed_per_rev
    label: Feed per Revolution
    datatype: float
    unit: mm/rev
    type: range
  doc_axial:
    id: doc_axial
    label: Depth of Cut (axial)
    datatype: float
    unit: mm
    type: range
  doc_radial:
    id: doc_radial
    label: Depth of Cut (radial)
    datatype: float
    unit: mm
    type: range
  doc:
    id: doc
    label: Depth of Cut
    datatype: float
    unit: mm
    type: range
  workpiece_diameter:
    id: workpiece_diameter
    label: Workpiece Diameter
    datatype: float
    unit: mm
    type: default
  tool_diameter:
    id: tool_diameter
    label: Tool Diameter
    datatype: float
    unit: mm
    type: default
  tool_tooth_count:
    id: tool_tooth_count
    label: Tool Tooth Count
    datatype: int
    type: default
  tool_material:
    id: tool_material
    label: Tool Material
    datatype: text_suggestions
    type: default
    options:
      - Carbide (P40)
      - Carbide
      - MCD
      - Ceramic
      - PCD
  tool_offset:
    id: tool_offset
    label: Tool Offset
    datatype: float
    unit: mm
    type: default
  coolant:
    id: coolant
    label: Coolant
    datatype: dropdown
    type: default
    options:
      - Dry
      - Air
      - MMQ
      - Flood
      - Oil
  sth_mac:
    id: sth_mac
    label: STH Mac Address
    datatype: text
    type: implementation
  stu_mac:
    id: stu_mac
    label: STU Mac Address
    datatype: text
    type: implementation
  tool_breakage:
    id: tool_breakage
    label: Tool Breakage
    datatype: boolean
    type: default
  first_tool_wear_exceeded:
    id: first_tool_wear_exceeded
    label: Tool Wear Exceeded (First Peripheral CE)
    datatype: boolean
    type: default
  first_wear_mark_width:
    id: first_wear_mark_width
    label: Avg. Wear Mark Width (First Peripheral CE)
    datatype: float
    unit: mm
    type: default
  first_max_wear_mark_width:
    id: first_max_wear_mark_width
    label: Max. Wear Mark Width (First Peripheral CE)
    datatype: float
    unit: mm
    type: default
  second_wear_mark_width:
    id: second_wear_mark_width
    label: Avg. Wear Mark Width (Second Peripheral CE)
    datatype: float
    unit: mm
    type: default
  second_max_wear_mark_width:
    id: second_max_wear_mark_width
    label: Max. Wear Mark Width (Second Peripheral CE)
    datatype: float
    unit: mm
    type: default
  second_tool_wear_exceeded:
    id: second_tool_wear_exceeded
    label: Tool Wear Exceeded (Second Peripheral CE)
    datatype: boolean
    type: default
  twm_layer:
    id: twm_layer
    label: Layer Number
    datatype: int
    type: default
  pictures:
    id: pictures
    label: Pictures
    datatype: file
    type: default
  comment:
    id: comment
    label: Comment
    datatype: text_box
    type: default
  direction:
    id: direction
    label: Milling Direction
    datatype: dropdown
    type: default
    options:
      - Climb
      - Conventional
  n_cuts:
    id: n_cuts
    label: Number of Cuts in Measurement
    datatype: int
    type: default
  n_measurement:
    id: n_measurement
    label: Measurement Number
    datatype: int
    type: default
  first_pictures:
    id: first_pictures
    label: Pictures of First Peripheral Cutting Edge
    datatype: file
    type: default
  second_pictures:
    id: second_pictures
    label: Pictures of Second Peripheral Cutting Edge
    datatype: file
    type: default
categories:
  general: General
  hardware: Hardware
  process: Process
  files: Files
  additional: Additional
  results: Results
  first_ce: First Cutting Edge
  second_ce: Second Cutting Edge
lists:
  requirement:
    - Required
    - Optional
    - Hidden
    - Restricted
  coolant:
    - Dry
    - Air
    - MMQ
    - Flood
    - Oil
  institution:
    - TU Wien
    - TU Darmstadt
  workpiece_material:
    - C45
    - Steel
  tool_material:
    - Carbide (P40)
    - Carbide
    - MCD
    - Ceramic
    - PCD
  process:
    - Milling
    - Drilling
    - Grinding
    - Turning
    - Reaming
    - Thread Cutting
    - Thread Forming
    - Thread Milling
  direction:
    - Climb
    - Conventional
profiles:
  twm1:
    id: twm_cirp_tool1
    name: CIRP TWM 1 (ae=2mm)
    pre:
      general:
        person:
          required: required
          description: Person responsible for the measurement.
        institution:
          required: required
          description: Institution at which the measurement is captured.
        machine:
          required: required
          description: Machine tool used for the measurement.
        experiment:
          required: required
          description: Experiment number or ID to identify the measurement.
        process:
          required: restricted
          default: Milling
          description: Measured process.
      process:
        workpiece_material:
          required: restricted
          default: '1.2379'
          description: Material of the workpiece.
        cutting_speed:
          required: restricted
          default: 80
        feed_per_tooth:
          required: restricted
          default: 0.05
        doc_axial:
          required: restricted
          default: 5
        doc_radial:
          required: restricted
          default: 2
        tool_diameter:
          required: restricted
          default: 10
        tool_tooth_count:
          required: restricted
          default: 2
        tool_material:
          required: restricted
          default: Carbide (P40)
        coolant:
          required: restricted
          default: Dry
      hardware:
        sth_mac:
          required: required
          description: MAC Address of the STH. Will be automatically set.
        stu_mac:
          required: required
          description: MAC Address of the STU. Will be automatically set.
    post:
      results:
        n_cuts:
          required: required
          default: 3
          description: Number of cuts in current measurement file
        n_measurement:
          required: required
          description: Measurement number in experiment
      first_ce:
        first_wear_mark_width:
          required: required
          description: Measured avg. width of the wear mark on the first peripheral cutting edge
        first_max_wear_mark_width:
          required: required
          description: Measured max. width of the wear mark on the first peripheral cutting edge
        first_tool_wear_exceeded:
          required: required
          default: 'false'
          description: Has the tool exceeded the maximum wear on the first peripheral cutting edge?
        first_pictures:
          required: required
          description: Pictures of the first peripheral cutting edge
      second_ce:
        second_wear_mark_width:
          required: required
          description: Measured avg. width of the wear mark on the second peripheral cutting edge
        second_max_wear_mark_width:
          required: required
          description: Measured max. width of the wear mark on the second peripheral cutting edge
        second_tool_wear_exceeded:
          required: required
          default: 'false'
          description: Has the tool exceeded the maximum wear on the second peripheral cutting edge?
        second_pictures:
          required: required
          description: Pictures of the second peripheral cutting edge
      additional:
        comment:
          required: optional
  twm2:
    id: twm_cirp_tool2
    name: CIRP TWM 2 (ae=10mm)
    pre:
      general:
        person:
          required: required
          description: Person responsible for the measurement.
        institution:
          required: required
          description: Institution at which the measurement is captured.
        machine:
          required: required
          description: Machine tool used for the measurement.
        experiment:
          required: required
          description: Experiment number or ID to identify the measurement.
        process:
          required: restricted
          default: Milling
          description: Measured process.
      process:
        workpiece_material:
          required: restricted
          default: '1.2379'
          description: Material of the workpiece.
        cutting_speed:
          required: restricted
          default: 80
        feed_per_tooth:
          required: restricted
          default: 0.05
        doc_axial:
          required: restricted
          default: 5
        doc_radial:
          required: restricted
          default: 10
        tool_diameter:
          required: restricted
          default: 10
        tool_tooth_count:
          required: restricted
          default: 2
        tool_material:
          required: restricted
          default: Carbide (P40)
        coolant:
          required: restricted
          default: Dry
      hardware:
        sth_mac:
          required: required
          description: MAC Address of the STH. Will be automatically set.
        stu_mac:
          required: required
          description: MAC Address of the STU. Will be automatically set.
    post:
      results:
        n_cuts:
          required: required
          default: 2
          description: Number of cuts in current measurement file
        n_measurement:
          required: required
          description: Measurement number in experiment
      first_ce:
        first_wear_mark_width:
          required: required
          description: Measured avg. width of the wear mark on the first peripheral cutting edge
        first_max_wear_mark_width:
          required: required
          description: Measured max. width of the wear mark on the first peripheral cutting edge
        first_tool_wear_exceeded:
          required: required
          default: 'false'
          description: Has the tool exceeded the maximum wear on the first peripheral cutting edge?
        first_pictures:
          required: required
          description: Pictures of the first peripheral cutting edge
      second_ce:
        second_wear_mark_width:
          required: required
          description: Measured avg. width of the wear mark on the second peripheral cutting edge
        second_max_wear_mark_width:
          required: required
          description: Measured max. width of the wear mark on the second peripheral cutting edge
        second_tool_wear_exceeded:
          required: required
          default: 'false'
          description: Has the tool exceeded the maximum wear on the second peripheral cutting edge?
        second_pictures:
          required: required
          description: Pictures of the second peripheral cutting edge
      additional:
        comment:
          required: optional
  milling:
    id: milling
    name: Milling (Generic)
    pre:
      general:
        person:
          required: optional
          description: Person responsible for the measurement.
        institution:
          required: optional
          description: Institution at which the measurement is captured.
        machine:
          required: optional
          description: Machine tool used for the measurement.
        experiment:
          required: optional
          description: Experiment number or ID to identify the measurement.
        process:
          required: optional
          default: Milling
          description: Measured process.
      process:
        workpiece_material:
          required: optional
          description: Material of the workpiece.
        cutting_speed:
          required: optional
        feed_per_tooth:
          required: optional
        doc_axial:
          required: optional
        doc_radial:
          required: optional
        tool_diameter:
          required: optional
        tool_tooth_count:
          required: optional
        tool_material:
          required: optional
        tool_offset:
          required: optional
          description: Tool offset from the control.
        coolant:
          required: optional
      hardware:
        sth_mac:
          required: required
          description: MAC Address of the STH. Will be automatically set.
        stu_mac:
          required: required
          description: MAC Address of the STU. Will be automatically set.
    post:
      general:
        pictures:
          required: optional
          description: Pictures of the experiment; will be stored in the .hdf5 file.
        comment:
          required: optional
